# Generated by Django 6.0.5 on 2026-05-05 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Короткое название проекта. Отображается в карточке на странице /cases/ и в заголовке страницы кейса. Пример: «SEO под ключ для интернет-магазина стройматериалов»', max_length=200, verbose_name='Заголовок кейса')),
                ('slug', models.SlugField(blank=True, help_text='Часть адреса страницы. Заполняется автоматически из заголовка. Можно изменить вручную — только латиница, цифры и дефисы. Пример: seo-stroymaterialy', max_length=200, unique=True, verbose_name='URL (slug)')),
                ('service', models.CharField(choices=[('avito_ads', 'Создание и ведение рекламной кампании'), ('avito_day', 'Авитолог на день'), ('avito_consult', 'Консультация Авитолога'), ('avito_autoload', 'Создание автозагрузочных файлов'), ('shop', 'Разработка интернет-магазина'), ('landing', 'Разработка лендинга'), ('website', 'Разработка сайта'), ('html_css', 'Верстка сайтов'), ('seo_setup', 'Внутренняя настройка СЕО'), ('seo_full', 'Ведение проекта под ключ'), ('seo_top', 'Вывод сайта в топ Яндекса'), ('direct_ads', 'Ведение рекламных кампаний')], help_text='Выберите услугу, которая была оказана клиенту. Используется для фильтрации кейсов.', max_length=50, verbose_name='Услуга')),
                ('direction', models.CharField(choices=[('avito', 'Авито'), ('dev', 'Разработка'), ('seo', 'СЕО'), ('direct', 'Яндекс Директ')], help_text='Категория кейса для сайдбара и фильтров. Авито / SEO / Яндекс.Директ / Разработка.', max_length=20, verbose_name='Направление')),
                ('industry', models.CharField(blank=True, help_text='Сфера бизнеса клиента. Пример: Строительство, Медицина, Интернет-магазин, HoReCa. Необязательное поле.', max_length=100, verbose_name='Отрасль')),
                ('description', models.TextField(help_text='1–2 предложения о проекте. Отображается в карточке на странице /cases/ и в превью при наведении. Пример: «Вывели сайт в топ-3 по 47 запросам за 4 месяца»', verbose_name='Короткое описание')),
                ('cover', models.ImageField(blank=True, help_text='Изображение для карточки кейса. Рекомендуемый размер: 1200×800 px, формат JPG или PNG. Если не загружена — показывается серый блок-заглушка.', null=True, upload_to='cases/covers/', verbose_name='Обложка')),
                ('hero_bg', models.ImageField(blank=True, help_text='Большое фото на весь экран в начале страницы кейса. Рекомендуемый размер: 1920×1080 px. Если не загружено — фон будет тёмный градиент.', null=True, upload_to='cases/heroes/', verbose_name='Фоновое изображение героя')),
                ('client_url', models.URLField(blank=True, help_text='Ссылка на сайт клиента. Показывается в герое страницы кейса кнопкой «Перейти на сайт». Пример: https://example.ru. Необязательное поле.', verbose_name='Сайт клиента')),
                ('year', models.CharField(blank=True, help_text='Год выполнения проекта. Показывается в герое рядом с тегами. Пример: 2024', max_length=10, verbose_name='Год проекта')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для поисковых систем. Если не заполнен — используется «Заголовок кейса». Рекомендуемая длина: 50–70 символов.', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Описание страницы для поисковых систем. Если не заполнено — используется «Короткое описание». Рекомендуемая длина: 120–160 символов.', verbose_name='Meta Description')),
                ('is_published', models.BooleanField(default=False, help_text='Включите, чтобы кейс появился на сайте. Пока галочка не стоит — кейс виден только в админке.', verbose_name='Опубликован')),
                ('published_at', models.DateField(default=django.utils.timezone.now, help_text='Определяет порядок в списке — новые кейсы идут выше. Подставляется автоматически, можно изменить вручную.', verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='CaseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('intro', 'Вводный текст'), ('task_resume', 'Задача + резюме проекта'), ('tasks_grid', 'Сетка задач (что мы решали)'), ('content_full', 'Контент-блок: на всю ширину'), ('content_two', 'Контент-блок: две колонки'), ('metrics', 'Результаты / цифры'), ('team', 'Команда'), ('cta', 'Призыв к действию (CTA)')], help_text='Выберите тип — ниже появятся только нужные поля.', max_length=30, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, help_text='Подставляется автоматически. Блоки отображаются по возрастанию этого числа.', verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, help_text='Снимите галочку, чтобы временно скрыть блок не удаляя его.', verbose_name='Показывать на сайте')),
                ('intro_text', models.TextField(blank=True, help_text='Крупный абзац в начале страницы. Описывает контекст: кто клиент, какая была ситуация, почему обратились. Длина: 3–6 предложений.', verbose_name='Вводный текст')),
                ('task_text', models.TextField(blank=True, help_text='Одна–две фразы: что именно попросил сделать клиент. Показывается в акцентном блоке слева. Пример: «Вывести сайт в топ-10 по 50 целевым запросам за 6 месяцев»', verbose_name='Задача заказчика')),
                ('tasks_title', models.CharField(blank=True, help_text='Заголовок над сеткой карточек. Пример: «Какие задачи мы решали в проекте с Ивановым»', max_length=300, verbose_name='Заголовок (сетка задач)')),
                ('cf_label', models.CharField(blank=True, help_text='Маленький текст над заголовком. Пример: «SEO», «Сайты»', max_length=100, verbose_name='Лейбл категории')),
                ('cf_title', models.CharField(blank=True, help_text='Крупный заголовок. Пример: «Собрали семантическое ядро из 850 запросов»', max_length=300, verbose_name='Заголовок блока')),
                ('cf_text_main', models.TextField(blank=True, help_text='Главный абзац — 2–4 предложения, суть работы.', verbose_name='Основной текст')),
                ('cf_text_secondary', models.TextField(blank=True, help_text='Второй абзац — детали, подробности. Необязательное поле.', verbose_name='Дополнительный текст')),
                ('cf_image', models.ImageField(blank=True, help_text='Скриншот или иллюстрация. Показывается справа от текста. Рекомендуется: минимум 800×600 px.', null=True, upload_to='cases/blocks/', verbose_name='Изображение')),
                ('cf_link_text', models.CharField(blank=True, help_text='Подпись перед ссылкой. Пример: «Вот посмотрите:»', max_length=200, verbose_name='Текст ссылки')),
                ('cf_link_url', models.URLField(blank=True, help_text='Адрес сайта или страницы. Пример: https://client-site.ru', verbose_name='URL ссылки')),
                ('left_label', models.CharField(blank=True, help_text='Необязательное поле.', max_length=100, verbose_name='Лейбл (левая колонка)')),
                ('left_title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (левая колонка)')),
                ('left_text_main', models.TextField(blank=True, verbose_name='Основной текст (левая колонка)')),
                ('left_text_secondary', models.TextField(blank=True, help_text='Необязательное поле.', verbose_name='Дополнительный текст (левая колонка)')),
                ('left_link_text', models.CharField(blank=True, help_text='Необязательное поле.', max_length=200, verbose_name='Текст ссылки (левая колонка)')),
                ('left_link_url', models.URLField(blank=True, help_text='Необязательное поле.', verbose_name='URL ссылки (левая колонка)')),
                ('right_label', models.CharField(blank=True, help_text='Необязательное поле.', max_length=100, verbose_name='Лейбл (правая колонка)')),
                ('right_title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (правая колонка)')),
                ('right_text_main', models.TextField(blank=True, verbose_name='Основной текст (правая колонка)')),
                ('right_text_secondary', models.TextField(blank=True, help_text='Необязательное поле.', verbose_name='Дополнительный текст (правая колонка)')),
                ('right_link_text', models.CharField(blank=True, help_text='Необязательное поле.', max_length=200, verbose_name='Текст ссылки (правая колонка)')),
                ('right_link_url', models.URLField(blank=True, help_text='Необязательное поле.', verbose_name='URL ссылки (правая колонка)')),
                ('metrics_title', models.CharField(blank=True, help_text='Пример: «Немного цифр», «Результат работ»', max_length=200, verbose_name='Заголовок блока результатов')),
                ('metrics_subtitle', models.CharField(blank=True, help_text='Одна–две строки под заголовком. Необязательное поле.', max_length=300, verbose_name='Подзаголовок')),
                ('cta_title', models.CharField(blank=True, help_text='Крупный заголовок. Пример: «Заказать проект», «Есть похожая задача?»', max_length=200, verbose_name='Заголовок CTA')),
                ('cta_text', models.TextField(blank=True, help_text='1–2 предложения под заголовком.', verbose_name='Текст CTA')),
                ('cta_btn_text', models.CharField(blank=True, default='Написать', help_text='Надпись на кнопке. По умолчанию: «Написать»', max_length=100, verbose_name='Текст кнопки')),
                ('cta_btn_url', models.CharField(blank=True, default='#contact', help_text='Куда ведёт кнопка. Можно указать якорь (#contact) или полный URL.', max_length=200, verbose_name='Ссылка кнопки')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='cases.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Блок кейса',
                'verbose_name_plural': 'Блоки кейса',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Число или короткий текст. Примеры: «+142%», «топ-3», «4 мес»', max_length=50, verbose_name='Значение')),
                ('label', models.CharField(help_text='Что означает это число. Пример: «рост трафика», «позиции в Яндексе»', max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cases.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MetricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Число или текст. Примеры: «+142», «топ-3»', max_length=50, verbose_name='Значение')),
                ('unit', models.CharField(blank=True, help_text='После числа. Примеры: «%», «мес», «тыс». Можно оставить пустым.', max_length=20, verbose_name='Единица измерения')),
                ('label', models.CharField(help_text='Пример: «рост органического трафика»', max_length=150, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_items', to='cases.caseblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Пример: «Старт работ», «Сдача проекта», «Длительность»', max_length=100, verbose_name='Метка')),
                ('value', models.CharField(help_text='Пример: «январь 2024», «6 месяцев»', max_length=100, verbose_name='Значение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_items', to='cases.caseblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Строка резюме',
                'verbose_name_plural': 'Резюме проекта',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Дополнительные метки для фильтрации. Можно выбрать несколько. Теги создаются отдельно в разделе «Теги».', to='cases.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Пример: «Собрали семантику», «Устранили технические ошибки»', max_length=200, verbose_name='Заголовок карточки')),
                ('text', models.TextField(blank=True, help_text='Краткое описание. Пример: «Подобрали 300 ключевых запросов с учётом региона»', verbose_name='Текст карточки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='cases.caseblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Карточка задачи',
                'verbose_name_plural': 'Карточки задач',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: «Иван Петров»', max_length=100, verbose_name='Имя')),
                ('role', models.CharField(help_text='Пример: «SEO-специалист», «Копирайтер»', max_length=150, verbose_name='Роль')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cases.caseblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
            },
        ),
    ]