# Generated by Django 6.0.4 on 2026-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('service', models.CharField(choices=[('avito_ads', 'Создание и ведение рекламной кампании Авито'), ('seo_full', 'СЕО под ключ'), ('seo_top', 'Вывод сайта в топ Яндекса'), ('direct_ads', 'Ведение рекламных кампаний в Яндекс Директ'), ('landing', 'Разработка лендинга'), ('shop', 'Разработка интернет-магазина'), ('website', 'Разработка сайта')], max_length=50, verbose_name='Услуга')),
                ('direction', models.CharField(choices=[('avito', 'Авито'), ('seo', 'СЕО'), ('direct', 'Яндекс.Директ'), ('dev', 'Разработка')], max_length=20, verbose_name='Направление')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Отрасль')),
                ('description', models.TextField(verbose_name='Короткое описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cases/covers/', verbose_name='Обложка')),
                ('metrics', models.JSONField(default=list, help_text='Список строк: ["+142% заявок", "-31% лид"]', verbose_name='Метрики')),
                ('blocks', models.JSONField(default=list, verbose_name='Блоки страницы')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('tags', models.ManyToManyField(blank=True, to='cases.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
