# Generated by Django 6.0.4 on 2026-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='blocks',
            field=models.JSONField(blank=True, default=list, verbose_name='Блоки страницы'),
        ),
        migrations.AlterField(
            model_name='case',
            name='metrics',
            field=models.JSONField(blank=True, default=list, help_text='Список строк: ["+142% заявок", "-31% лид"]', verbose_name='Метрики'),
        ),
    ]
