# Generated by Django 6.0.4 on 2026-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_hero_arrow_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cover',
            field=models.URLField(blank=True, help_text='Ссылка на изображение для карточки кейса. Пример: https://example.com/image.jpg', verbose_name='Обложка (URL)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hero_bg',
            field=models.URLField(blank=True, help_text='Ссылка на фоновое изображение героя. Пример: https://example.com/hero.jpg', verbose_name='Фоновое изображение героя (URL)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hero_image',
            field=models.URLField(blank=True, help_text='Скриншот статистики для правой части героя. Если не заполнено — показывается стандартный дашборд.', verbose_name='Изображение в герое (URL)'),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='block_type',
            field=models.CharField(choices=[('intro', 'Вводный текст'), ('task_resume', 'Задача + резюме проекта'), ('tasks_grid', 'Сетка задач (что мы решали)'), ('content_two', 'Контент-блок: две колонки'), ('metrics', 'Результаты / цифры'), ('team', 'Команда'), ('cta', 'Призыв к действию (CTA)')], help_text='Выберите тип — ниже появятся только нужные поля.', max_length=30, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='cf_image',
            field=models.URLField(blank=True, help_text='Ссылка на изображение. Показывается справа от текста.', verbose_name='Изображение (URL)'),
        ),
    ]
