# Generated by Django 6.0.4 on 2026-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_resumeitem_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cover',
            field=models.CharField(blank=True, help_text='Ссылка на изображение для карточки кейса. Пример: https://example.com/image.jpg', max_length=500, verbose_name='Обложка (URL)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hero_arrow_svg',
            field=models.CharField(blank=True, help_text='SVG с прозрачным фоном того же размера, что и основное изображение. Накладывается поверх. Если не заполнено — стрелка не показывается.', max_length=500, verbose_name='Стрелка поверх (SVG, URL)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hero_bg',
            field=models.CharField(blank=True, help_text='Ссылка на фоновое изображение героя. Пример: https://example.com/hero.jpg', max_length=500, verbose_name='Фоновое изображение героя (URL)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Скриншот статистики для правой части героя. Если не заполнено — показывается стандартный дашборд.', max_length=500, verbose_name='Изображение в герое (URL)'),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='cf_image',
            field=models.CharField(blank=True, help_text='Ссылка на изображение. Показывается справа от текста.', max_length=500, verbose_name='Изображение (URL)'),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='cta_image',
            field=models.CharField(blank=True, help_text='Картинка в левой части CTA-блока. Необязательное поле.', max_length=500, verbose_name='Изображение CTA (URL)'),
        ),
        migrations.AlterField(
            model_name='devcaseimage',
            name='url',
            field=models.CharField(help_text='Прямая ссылка на изображение. Пример: https://example.com/screen1.jpg', max_length=500, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок строки'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='text',
            field=models.CharField(blank=True, help_text='Мелкий шрифт. Пример: «месяца», «с января»', max_length=100, verbose_name='Текст (мелкий)'),
        ),
    ]
